# Generated by Django 2.2.5 on 2019-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ennarroot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=1000)),
                ('capacity', models.CharField(default='', max_length=1000)),
                ('workingpressure', models.CharField(default='', max_length=1000)),
                ('fuel', models.CharField(default='', max_length=1000)),
                ('model_series', models.CharField(default='', max_length=1000)),
                ('product_image', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
