# Generated by Django 2.2.5 on 2019-10-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=1000)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('posted_date', models.CharField(max_length=250)),
            ],
        ),
    ]
