# Generated by Django 2.2.5 on 2019-10-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='posted_date_time',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blogs',
            name='posted_day',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blogs',
            name='posted_year',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='posted_date',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='topic',
            field=models.CharField(default='', max_length=250),
        ),
    ]
