# Generated by Django 2.2.5 on 2019-10-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191002_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='posted_day',
            new_name='posted_month',
        ),
    ]
